import type { SoraOptions } from '@/components/Dashboard'

export const DEFAULT_OPTIONS: SoraOptions = {
  prompt: 'A breathtaking cinematic scene of a futuristic city at sunset, flying cars zipping between glass skyscrapers, vibrant colors, ultra-detailed, 8K, masterful lighting, trending on ArtStation',
  negative_prompt: 'blurry, low-res, dark, extra limbs, cropped, watermark, text, signature, logo',
  use_negative_prompt: true,
  seed: 1337,
  steps: 30,
  guidance_scale: 7.5,
  width: 1024,
  height: 576,
  use_dimensions: true,
  aspect_ratio: '16:9',
  cfg_rescale: 0.7,
  style_preset: {
    category: 'Photography & Cinematic',
    style: 'cinematic'
  },
  use_style_preset: false,
  quality: 'high',
  temperature: 1.1,
  dynamic_range: 'HDR',
  output_format: 'png',
  duration_seconds: 5,
  fps: 30,
  motion_strength: 0.85,
  camera_motion: 'dolly_in',
  motion_direction: 'forward',
  camera_angle: 'low',
  shot_type: 'wide',
  subject_focus: 'center',
  composition_rules: [],
  lighting: '',
  color_grade: 'default (no specific color grading)',
  depth_of_field: 'shallow',
  lens_type: 'default',
  frame_interpolation: 'smooth',
  upscale: 2,
  safety_filter: 'moderate',
  made_out_of: 'default',
  environment: 'default',
  use_signature: false,
  blur_style: 'default',
  aperture: 'default (auto aperture)',
  use_motion_animation: false,
  use_enhancement_safety: false,
  camera_type: 'default (auto/any camera)',
  use_settings_location: false,
  year: new Date().getFullYear(),
  use_season: false,
  use_atmosphere_mood: false,
  use_subject_mood: false,
  use_sword_type: false,
  use_core_settings: false,
  use_dimensions_format: false,
  use_lighting: false,
  use_material: false,
  use_secondary_material: false,
  use_color_grading: false,
  use_environment: false,
  use_time_of_year: false,
  use_character_mood: false,
  use_sword_details: false,
  prevent_deformities: false,
  use_upscale_factor: false,
  use_safety_filter: false,
  keep_typography_details: false,
  use_face_enhancements: false,
  add_same_face: false,
  dont_change_face: false,
  use_subject_gender: false,
  use_makeup_style: false,
  use_quality_booster: false,
  enhance_object_reflections: false,
  keep_key_details: false,
  use_black_and_white: false,
  use_location: false,
  use_special_effects: false,
  use_lut_preset: false,
  use_dnd_section: false,
  use_dnd_character_race: false,
  use_dnd_character_class: false,
  use_dnd_character_background: false,
  use_dnd_character_alignment: false,
  use_dnd_monster_type: false,
  use_dnd_environment: false,
  use_dnd_magic_school: false,
  use_dnd_item_type: false,
  use_camera_composition: false,
  use_camera_angle: false,
  use_lens_type: false,
  use_aperture: false,
  use_dof: false,
  use_blur_style: false,
  extended_motion_strength: false,
  extended_fps: false,
  use_duration: false,
}
