import React from 'react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { ScrollArea } from '@/components/ui/scroll-area';

interface DisclaimerModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

const text = `Intellectual Property & Software Disclaimer\n\nThis software and all related content, including but not limited to prompts, code, assets, data, and documentation (“the Software”), are provided for informational, educational, and creative purposes only.\n\nAll intellectual property rights in and to the Software remain with their respective owners and licensors.\nNo part of the Software may be used in violation of applicable laws or intellectual property rights.\n\nThe Software is provided “as is,” without warranty of any kind, express or implied, including but not limited to the warranties of merchantability, fitness for a particular purpose, and non-infringement.\nNo guarantee is given regarding the accuracy, completeness, performance, or fitness of the Software for any specific use.\n\nBy using the Software, you agree that:\n\n    You are solely responsible for how you use, share, or modify the Software and any outputs generated by it.\n\n    The creators, authors, maintainers, and licensors of the Software are not responsible or liable for any actions, damages, losses, legal claims, or consequences resulting from your use or misuse of the Software.\n\n    You will not use the Software for any unlawful, unethical, or infringing activities.\n\n    Any outputs, results, or creative works produced using the Software are subject to the same disclaimers and may be subject to third-party rights.\n\nUse of this Software is entirely at your own risk.\nIf you do not agree to these terms, do not use, copy, distribute, or modify the Software.`;

const DisclaimerModal: React.FC<DisclaimerModalProps> = ({ open, onOpenChange }) => (
  <Dialog open={open} onOpenChange={onOpenChange}>
    <DialogContent className="sm:max-w-2xl">
      <DialogHeader>
        <DialogTitle>Intellectual Property &amp; Software Disclaimer</DialogTitle>
      </DialogHeader>
      <ScrollArea className="h-[60vh] px-1">
        <p className="whitespace-pre-wrap text-sm">{text}</p>
      </ScrollArea>
    </DialogContent>
  </Dialog>
);

export default DisclaimerModal;
